routes/admin.php
<?php
Route::get('login', ['as' => 'admin.login', 'uses' => 'LoginController@showLoginForm']);
Route::post('login', ['uses' => 'LoginController@login']);

Route::group(['middleware' => ['admin.auth', 'access']], function () {
    Route::get('/', ['as' => 'admin.dashboard', 'uses' => 'DashboardController@index']);
    Route::post('logout', ['as' => 'admin.logout', 'uses' => 'LoginController@logout']);
    Route::get('crop', ['as' => 'admin.crop', 'uses' => 'CropController@edit']);
    Route::put('crop', ['as' => 'admin.crop.update', 'uses' => 'CropController@update']);
    Route::group(['prefix' => 'account'], function () {
        Route::get('/', ['as' => 'admin.profile', 'uses' => 'ProfileController@index']);
        Route::put('save-personal-data', ['as' => 'admin.save-personal-data', 'uses' => 'ProfileController@savePersonalData']);
        Route::get('change-password', ['as' => 'admin.change-password', 'uses' => 'ProfileController@changePassword']);
        Route::put('save-new-password', ['as' => 'admin.save-new-password', 'uses' => 'ProfileController@saveNewPassword']);
        Route::get('change-avatar', ['as' => 'admin.change-avatar', 'uses' => 'ProfileController@changeAvatar']);
        Route::put('save-new-avatar', ['as' => 'admin.save-new-avatar', 'uses' => 'ProfileController@saveNewAvatar']);
        Route::delete('delete-avatar', ['as' => 'admin.delete-avatar', 'uses' => 'ProfileController@deleteAvatar']);
    });

    Route::resource('pages', 'Content\PagesController', ['except' => ['show'], 'as' => 'admin']);
    Route::resource('cities', 'Dictionaries\CitiesController', ['except' => ['show'], 'as' => 'admin']);
    Route::resource('streets', 'Dictionaries\StreetsController', ['except' => ['show'], 'as' => 'admin']);
    Route::resource('departments', 'Dictionaries\DepartmentsController', ['except' => ['show'], 'as' => 'admin']);
    Route::resource('professions', 'Dictionaries\ProfessionsController', ['except' => ['show'], 'as' => 'admin']);

    Route::resource('cards', 'Cards\CardsController', ['except' => ['show'], 'as' => 'admin']);


    Route::resource('settings', 'SettingsController', ['only' => ['index', 'store'], 'as' => 'admin']);


    Route::resource('system-pages', 'Content\SystemPagesController', ['except' => ['show'], 'as' => 'admin']);
    Route::get('system-pages/{id}/delete-image', ['as' => 'admin.system-pages.delete-image', 'uses' => 'Content\SystemPagesController@deleteImage']);

    Route::resource('menu', 'MenuController', ['except' => ['show'], 'as' => 'admin']);


    Route::resource('roles', 'Users\RolesController', ['except' => ['show'], 'as' => 'admin']);
    Route::resource('customers', 'Users\CustomersController', ['except' => ['show'], 'as' => 'admin']);
    Route::get('customers/deleted', ['as' => 'admin.customers.deleted', 'uses' => 'Users\CustomersController@deleted']);
    Route::put('customers/{id}/restore', ['as' => 'admin.customers.restore', 'uses' => 'Users\CustomersController@restore']);
    Route::delete('customers/{id}/force-delete', ['as' => 'admin.customers.force-delete', 'uses' => 'Users\CustomersController@forceDelete']);
    Route::resource('managers', 'Users\ManagersController', ['except' => ['show'], 'as' => 'admin']);
    Route::get('managers/deleted', ['as' => 'admin.managers.deleted', 'uses' => 'Users\ManagersController@deleted']);
    Route::get('managers/{manager}/delete-avatar', ['as' => 'admin.managers.delete-image', 'uses' => 'Users\ManagersController@deleteAvatar']);
    Route::put('managers/{id}/restore', ['as' => 'admin.managers.restore', 'uses' => 'Users\ManagersController@restore']);
    Route::delete('managers/{id}/force-delete', ['as' => 'admin.managers.force-delete', 'uses' => 'Users\ManagersController@forceDelete']);

    Route::get('notifications', ['as' => 'admin.notifications', 'uses' => 'NotificationsController@index']);
    Route::get('notifications/read/{notification}', ['as' => 'admin.notifications.read', 'uses' => 'NotificationsController@read']);

    Route::resource('brands', 'Catalog\BrandsController', ['except' => ['show'], 'as' => 'admin']);
    Route::get('brands/{id}/delete-image', ['as' => 'admin.brands.delete-image', 'uses' => 'Catalog\BrandsController@deleteImage']);

    Route::resource('specifications', 'Catalog\SpecificationsController', ['except' => ['show', 'create', 'store', 'destroy'], 'as' => 'admin']);

    Route::resource('products', 'Catalog\ProductsController', ['except' => ['show'], 'as' => 'admin']);

    Route::get('products/excel', ['as' => 'admin.products.excel', 'uses' => 'Catalog\ProductsController@excel']);

    Route::resource('products-reviews', 'Catalog\ProductsReviewsController', ['except' => ['show'], 'as' => 'admin']);
    Route::get('products/{id}/delete-image', ['as' => 'admin.products.delete-image', 'uses' => 'Catalog\ProductsController@deleteImage']);

    Route::resource('rewards', 'Catalog\ProductsRewardsController', ['except' => ['show'], 'as' => 'admin']);
    Route::get('rewards/{id}/delete-image', ['as' => 'admin.rewards.delete-image', 'uses' => 'Catalog\ProductsRewardsController@deleteImage']);

    Route::get('visitors', ['as' => 'admin.visitors.index', 'uses' => 'Statistic\VisitorsController@index']);
    Route::get('hits', ['as' => 'admin.hits.index', 'uses' => 'Statistic\HitsController@index']);
    Route::get('refers', ['as' => 'admin.refers.index', 'uses' => 'Statistic\RefersController@index']);
    Route::get('fake-auth', ['as' => 'admin.fake-auth', 'uses' => 'Users\FakeAuthController@index']);

    Route::resource('orders', 'Orders\OrdersController', ['except' => ['show'], 'as' => 'admin']);
    Route::get('print-order/{id}', ['as' => 'admin.print-order.index', 'uses' => 'Orders\OrdersController@printOrder']);
});

routes/web.php
<?php
Route::patch('/', function () {
    if (request()->input('password') === config('db.security.bot-password')) {
        Session::put('protectionPassed', true);
        return redirect()->back();
    } else {
        abort(401);
    }
});
Route::group(['prefix' => config('prefix')], function () {
    Config::set('lang', Lang::getLocale());
    Auth::routes();

    Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
    Route::get('register/confirmation/{token}', ['as' => 'register.confirm', 'uses' => 'Auth\RegisterController@confirmation']);

    Route::any('/', ['as' => 'site.index', 'uses' => 'IndexController@show']);

    if (!Request::is('admin')) {
        #Route::get('{slug}', ['as' => 'site.pages.show', 'uses' => 'Content\PagesController@show']);
    }

    Route::get('/social/{provider}', ['as' => 'socials.redirect', 'uses' => 'Auth\LoginController@socials']);
    Route::get('/social/{provider}/callback', ['as' => 'socials.callback', 'uses' => 'Auth\LoginController@callback']);
    Route::get('/forgot-password', ['as' => 'forgot-password', 'uses' => 'Auth\ForgotPasswordController@index']);
    Route::post('/forgot-password', ['as' => 'password.email.custom', 'uses' => 'Auth\ForgotPasswordController@send']);
    // Client side routers

    // Votings
    Route::get('/voting', 'VotingsController@index')->name('votings');
    Route::post('/voting', 'VotingsController@store')->name('votingPOST');
    //Subscribe action
    Route::post('subscribe', ['as' => 'subscribe', 'uses' => 'SubscribeController@index']);
    //Content block
    Route::get('/blog', 'Content\ContentController@index')->name('blog');
    Route::get('/blog/ajax', 'Content\ContentController@index')->name('blog.ajax');

    //blog
    Route::get('/blog/{type}', 'Content\BlogController@index')->name('content')->where('type', 'events|news|articles');
    Route::get('/blog/{type}/{category}', 'Content\BlogController@category')->name('content.category')->where('type', 'events|news|articles');
    Route::get('/blog/{type}/{category}/{slug}', 'Content\BlogController@show')->name('content.show')->where('type', 'events|news|articles');

    //Contacts
    Route::get('/contacts', 'ContactsController@index')->name('contacts');
    // About us
    Route::get('/about-us', 'AboutUs\About@index')->name('about');
    Route::get('/about-us/ajax', 'AboutUs\About@index')->name('about.ajax');
    Route::get('/about-us/who-are-we', 'AboutUs\WhoRweController@index')->name('whoRwe');
    Route::get('/about-us/our-experts', 'AboutUs\ExpertsContactsController@index')->name('experts');
    Route::get('/about-us/our-directors', 'AboutUs\TeamController@index')->name('team');
    Route::get('/about-us/quality', 'AboutUs\QualityController@index')->name('quality');


    //Delivery
    Route::get('/payment-and-delivery', 'PaymentDeliveryController@index')->name('paymentDelivery');

    Route::get('/reviews', 'ReviewsController@index')->name('reviews');


    Route::group(['middleware' => ['auth'], 'prefix' => 'profile'], function () {
    //Profile
    Route::get('/', 'ProfileController@index')->name('profile');
    Route::get('/edit-password', 'ProfileController@indexPassword')->name('profile.editPassword');
    Route::get('/favorites', 'ProfileController@indexFavorites')->name('profile.favorites');
    Route::get('/favorites-clear', 'ProfileController@clearFavorites')->name('profile.favorites.clear');
    Route::get('/orders', 'ProfileController@indexOrders')->name('profile.orders');
    Route::get('/wait', 'ProfileController@indexWait')->name('profile.wait');
    Route::get('/wait-clear', 'ProfileController@clearWait')->name('profile.wait.clear');
    Route::get('/settings', 'ProfileController@indexSettings')->name('profile.settings');
    Route::post('/edit-password', 'ProfileController@updatePassword')->name('profile.newPass');
    Route::post('/', 'ProfileController@update')->name('profile.profileUpd');
    });

    //Products
    Route::paginate('/products', 'Catalog\ProductsController@index')->name('products');
    Route::paginate('/products/filter/{filters}', 'Catalog\ProductsController@index')
    ->where('filters', '.*')
    ->name('products-with-filter');
    Route::get('/products/{slug}', 'Catalog\ProductsController@show')->name('product');
    Route::get('/cart', 'Catalog\CartController@index')->name('cart');
    Route::get('/compilation/{slug}/products', 'Catalog\ProductsController@compilation')->name('compilation');
    Route::get('/compilation/{slug}/products/filter/{filters}', 'Catalog\ProductsController@compilation')
    ->where('filters', '.*')
    ->name('compilation-with-filter');

    //Ordering
    Route::match(['GET', 'POST'], '/checkout', 'Catalog\OrderController@index')->name('ordering');
    Route::match(['GET', 'POST'], '/checkout/step-1/{id}', 'Catalog\OrderController@index')->name('ordering.step-1');
    Route::match(['GET', 'POST'], '/checkout/step-2/{id}', 'Catalog\OrderController@step2')->name('ordering.step-2');
    Route::match(['GET', 'POST'], '/checkout/step-3/{id}', 'Catalog\OrderController@step3')->name('ordering.step-3');
    Route::any('/checkout/check-payment', 'Catalog\OrderController@checkPayment')->name('check-payment');
    Route::any('/checkout/check-payment/portmone', 'Catalog\OrderController@checkPaymentPortmone')->name('check-payment.portmone');

    //Brand presentation
    Route::get('/brand/{slug}/products', 'Catalog\BrandsPresentController@index')->name('brand.products');
    Route::get('/brand/{slug}/products/filter/{filters}', 'Catalog\BrandsPresentController@index')
    ->where('filters', '.*')
    ->name('brand.products-with-filter');
    Route::get('/presentation/{slug}', 'Catalog\BrandsPresentController@product')->name('brand.present');


    Route::get('/brands', 'Catalog\BrandsController@index')->name('brands');
    Route::get('/brands/filter/{filters}', 'Catalog\BrandsController@index')
    ->where('filters', '.*')
    ->name('brands-with-filter');
    Route::get('/brands/ajax', 'Catalog\BrandsController@index')->name('brands.ajax');

    //Search
    Route::get('/products-search', 'Catalog\ProductsController@search')->name('products.search');

    //Where buy page
    Route::get('/where-buy', 'WhereBuyController@index')->name('where-buy');

    Route::get('/sitemap', 'SitemapController@index')->name('sitemap');
    Route::get('/sitemap-xml', 'SitemapController@xml')->name('sitemap');


    Route::get('/age-check', 'AgeCheck@index')->name('age-check');
    Route::get('/age-check/{access}', 'AgeCheck@access')->name('age-check-access');
    Route::get('/age-check-denied', 'AgeCheck@denied')->name('age-check-denied');

    //Fake login
    Route::get('/fake-login', 'FakeLoginController@index')->name('fake-login');


    // Text pages
    if (!Request::is('admin')) {
        Route::get('{slug}', 'Content\TextPageController@index')->name('text-page');
    }
});

app/Http/Controllers/Admin/Content/Articles/CommentsController.php
<?php

namespace App\Http\Controllers\Admin\Content\Articles;

use App\Helpers\Alert;
use App\Models\Article;
use App\Models\Comment;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Admin\Controller;

class CommentsController extends Controller
{

    protected $pageName = 'Отзывы о статьи';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $id)
    {
        $comments = Comment::getList($this->rowsCount,1, $idArticle = $id->input('idArticle'), $idUser = $id->input('idUser'));
        return view('admin.content.articles.comments.index', [
            'comments' => $comments,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $articles = Article::getList(100, 1);
        $users = User::all();
        $articlesArr = [];
        $usersArr = [];
        $usersArr[0] = '';
        foreach ($articles as $article) {
            $articlesArr[$article->id] = $article->current->name;
        }
        foreach ($users as $user) {
            $usersArr[$user->id] = $user->second_name . ' ' . $user->first_name;
        }
        view()->share('jsValidator', \JsValidator::make((new Comment())->rules()));
        return view('admin.content.articles.comments.create', ['articles' => $articlesArr, 'users' => $usersArr]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $comments = new Comment();
        $this->validate($request, $comments->rules());
        $comments->fill($request->input());
        $comments->position = 0;
        $comments->type = 1;
        $comments->created_at = $request->input('created_at');
        if ($request->input('user_id') == 0) {
            $comments->user_id = null;
        }
        $saved = $comments->save();
        Alert::afterCreating($saved);
        if ($saved) {
            return $this->redirectUserTo('articles-comments', $comments->id);
        }
        return redirect(route('admin.articles-comments.create'))->withInput();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function edit(Comment $articlesComment)
    {
        $article = Article::find($articlesComment->article_id);
        $user = User::find($articlesComment->user_id);
        view()->share('jsValidator', \JsValidator::make($articlesComment->rules()));
        return view('admin.content.articles.comments.update', ['comments' => $articlesComment, 'article' => $article, 'user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Comment $articlesComment)
    {
        $this->validate($request, $articlesComment->rules());
        $articlesComment->fill($request->input());
        $articlesComment->created_at = $request->input('created_at');
        $articlesComment->type = 1;
        $articlesComment->status = $request->input('status');
        $saved = $articlesComment->save();
        Alert::afterUpdating($saved);
        if ($saved) {
            return $this->redirectUserTo('articles-comments', $articlesComment->id);
        }
        return redirect(route('admin.articles-comments.edit', ['comments' => $articlesComment->id]))->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $articlesComment)
    {
        Alert::afterDeleting($articlesComment->delete());
        return redirect(route('admin.articles-comments.index'));
    }
}

resources/views/admin/content/events/comments/_form.blade.php
<?php
/** @var \App\Models\ArticlesCategory $object */
$object = isset($comments) ? $comments : null;
//dd($object);
?>
<div class="row">
    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-body">
                @include('admin.widgets.form.input', ['name' => 'text', 'label' => 'Текст комментария', 'object' => $object, 'options' => ['required']])
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="box box-warning">
            <div class="box-body">
                @include('admin.widgets.form.status', ['status' => old('status', isset($object) ? $object->status : 0)])
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="box box-info">
            <div class="box-body">
                @include('admin.widgets.form.date', ['name' => 'created_at', 'label' => 'Дата создания', 'object' => $object, 'options' => ['']])
                <div class="form-group  ">
                    <label class="control-label">Статья</label>
                    <div>
                        <a href="{{route('admin.news.edit', ['id' => $article->id])}}">{{$article->name}}</a>
                    </div>
                </div>
                <div class="form-group  ">
                    <label class="control-label">Пользователь</label>
                    <div>
                        @if(isset($user))
                            <a href="{{route('admin.customers.edit', ['id' => $user->id])}}">{{$user->first_name . ' ' . $user->second_name}}</a>
                        @else
                            <p>---</p>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/admin/content/events/comments/_formCreate.blade.php
<?php
/** @var \App\Models\ArticlesCategory $object */
$object = isset($comments) ? $comments : null;
//dd($object);
?>
<div class="row">
    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-body">
                @include('admin.widgets.form.input', ['name' => 'text', 'label' => 'Текст комментария', 'object' => $object, 'options' => ['required']])
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="box box-warning">
            <div class="box-body">
                @include('admin.widgets.form.status', ['status' => old('status', isset($object) ? $object->status : 0)])
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="box box-info">
            <div class="box-body">
                @include('admin.widgets.form.date', ['name' => 'created_at', 'label' => 'Дата комментария',])
                @include('admin.widgets.form.select', ['additionalClass' => 'articlesSelected', 'name' => 'article_id', 'label' => 'Статья',  'data' => $articles, 'options' => ['required']])
                @include('admin.widgets.form.select', ['name' => 'user_id', 'label' => 'Пользователь',  'data' => $users, 'options' => ['class' => 'form-control select2']])
            </div>
        </div>
    </div>
</div>

resources/views/admin/content/events/comments/create.blade.php
@extends('admin.layouts.main')
@section('content')
    {!! Form::open(['route' => 'admin.events-comments.store', 'files' => true]) !!}
    @include('admin.widgets.form.buttons', ['create' => true])
    @include('admin.content.events.comments._formCreate')
    @include('admin.widgets.form.buttons', ['create' => true])
    {!! Form::close() !!}
@stop

resources/views/admin/content/events/comments/index.blade.php
@extends('admin.layouts.main')

@section('custom-buttons')
    <a href="{{ route('admin.events-comments.create') }}" class="btn bg-olive btn-flat margin">Добавить</a>
@endsection

@section('content')
    @widget('filter', ['fields' => 'comments'])
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tr>
                            <th>Комментарий</th>
                            <th>Имя статьи</th>
                            <th>Имя пользователя</th>
                            <th>Статус</th>
                            <th></th>
                        </tr>
                        @foreach($comments AS $comment)
                            <tr>
                                <td width="60%">{!! $comment->text !!}</td>
                                <td width="10%"><a
                                            href="{{ route('admin.news.edit', ['article' => $comment->article->id]) }}">{{ substr($comment->article->current->name, 0, 25) }}
                                        ...</a></td>
                                @if(isset($comment->user_id))
                                    <td width="10%"><a href="{{ route('admin.customers.edit', ['user' => $comment->user->id]) }}">{{ $comment->user->first_name . ' ' . $comment->user->second_name }}</a></td>
                                @else
                                    <td>---------</td>
                                @endif

                                <td width="5%">@widget('status', ['status' => $comment->status, 'table' => 'comments', 'id' => $comment->id])</td>
                                <td width="5%">@widget('listButtons', ['routeBase' => 'events-comments.', 'id' => $comment->id, 'view' => false])</td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </div>
            <div class="text-center">{{ $comments->appends(Input::except('page'))->render() }}</div>
        </div>
    </div>
@endsection

resources/views/admin/content/events/comments/update.blade.php
@extends('admin.layouts.main')

@section('content')
    {!! Form::open(['route' => ['admin.events-comments.update', 'categories' => $comments->id], 'method' => 'PUT', 'files' => true]) !!}
        @include('admin.widgets.form.buttons')
        @include('admin.content.events.comments._form', ['comments' => $comments])
        @include('admin.widgets.form.buttons')
    {!! Form::close() !!}
@stop